"""Tour page content for Antigua Shore Excursion."""
from antigua_config import (
    ANTIGUAN_EXPERIENCE_ALT,
    ANTIGUAN_EXPERIENCE_IMG,
    BEACHES_ALT,
    BEACHES_IMG,
    CADES_REEF_ALT,
    CADES_REEF_IMG,
    CLASSIC_BEACH_ALT,
    CLASSIC_BEACH_IMG,
    HALF_DAY_KAYAK_ALT,
    HALF_DAY_KAYAK_IMG,
    HISTORY_CULTURE_ALT,
    HISTORY_CULTURE_IMG,
    INTRO_ALT,
    INTRO_IMG,
    KAYAK_SNORKEL_ALT,
    KAYAK_SNORKEL_IMG,
    NELSONS_DOCKYARD_ALT,
    NELSONS_DOCKYARD_IMG,
    PANORAMIC_ALT,
    PANORAMIC_IMG,
    SHIRLEY_HEIGHTS_ALT,
    SHIRLEY_HEIGHTS_IMG,
)
from antigua_helpers import content_tour_page


def all_tour_content() -> dict[str, str]:
    return {
        "the-antiguan-experience.html": content_tour_page(
            "The Antiguan Experience introduces cruise passengers to the island beyond the beach — a scenic drive through rolling countryside, a visit to a private home, a stop at a pineapple farm famous for Antigua's Black Pineapple, and a relaxing finish on a beautiful white-sand beach. It is one of the most popular culture-and-beach combinations from St John's.",
            [
                "4-hour format fits most Antigua port calls with return-to-ship buffer.",
                "Scenic drive through Antigua's lush interior and coastal villages.",
                "Pineapple farm visit with insight into Antigua's agricultural heritage.",
                "Beverages and lunch included on standard operator packages.",
                "Moderate activity — some walking at farm and beach stops.",
            ],
            [
                (ANTIGUAN_EXPERIENCE_IMG, ANTIGUAN_EXPERIENCE_ALT, "Island Countryside", "Rolling hills, fishing villages and tropical scenery across Antigua."),
                (INTRO_IMG, INTRO_ALT, "Pineapple Farm", "Learn about Antigua's famous Black Pineapple at a working farm."),
                (CLASSIC_BEACH_IMG, CLASSIC_BEACH_ALT, "Beach Finale", "Relax on pristine white sand with calm turquoise Caribbean water."),
            ],
            dict(
                best_for="First-time visitors wanting culture and beach",
                activity_level="Moderate",
                family="Excellent for mixed ages",
                popular="Culture tours, pineapple farm, beach days",
            ),
            ANTIGUAN_EXPERIENCE_IMG,
            ANTIGUAN_EXPERIENCE_ALT,
            badge="Best for First-Time Visitors",
            extra_links=[("antigua-port-guide.html", "Port Guide"), ("best-beaches-in-antigua-for-cruise-passengers.html", "Beach Guide")],
        ),
        "classic-beach-day.html": content_tour_page(
            "Classic Beach Day delivers exactly what many cruise passengers want from Antigua — a stress-free stretch of stunningly white sand at one of the island's top beaches. Loungers, calm turquoise water, refreshments and lunch are timed around your ship schedule so you can swim, sunbathe and return to St John's with confidence.",
            [
                "4 hours including beach time, refreshments and lunch.",
                "One of Antigua's finest white-sand beaches with calm swimming.",
                "Moderate activity — mostly relaxing with optional swimming.",
                "Beverage and lunch included on standard packages.",
                "Ideal when you want sun and sea without a long drive or hike.",
            ],
            [
                (CLASSIC_BEACH_IMG, CLASSIC_BEACH_ALT, "White Sand Paradise", "Powdery white sand and sheltered turquoise Caribbean water."),
                (BEACHES_IMG, BEACHES_ALT, "Beach Facilities", "Loungers and shade for a comfortable cruise-friendly beach day."),
                (CLASSIC_BEACH_IMG, CLASSIC_BEACH_ALT, "Calm Swimming", "Sheltered bays ideal for relaxed swimming from shore."),
            ],
            dict(
                best_for="Beach lovers and relaxed port days",
                activity_level="Moderate — mostly lounging",
                family="Excellent for families",
                popular="Beach days, swimming, sunbathing",
            ),
            CLASSIC_BEACH_IMG,
            CLASSIC_BEACH_ALT,
            badge="Best Beach Day",
            extra_links=[("best-beaches-in-antigua-for-cruise-passengers.html", "Beach Guide"), ("panoramic-antigua-and-beach-break.html", "Panoramic &amp; Beach")],
        ),
        "antigua-kayak-snorkel-and-beach.html": content_tour_page(
            "Antigua Kayak, Snorkel and Beach combines three highlights in one cruise-friendly itinerary — a drive through lush rainforest and fishing villages, kayaking in the sheltered waters of Cades Bay, snorkelling over the famous Cades Reef, and time to relax on a beautiful beach. It is the signature adventure combo for active passengers.",
            [
                "4 hours covering kayak, snorkel and beach segments.",
                "Kayak through Cades Bay mangroves and coastal lagoons.",
                "Snorkel Cades Reef — one of Antigua's premier reef systems.",
                "Beverage and lunch included; moderate fitness required.",
                "Small-group format with guides and cruise-timed returns.",
            ],
            [
                (KAYAK_SNORKEL_IMG, KAYAK_SNORKEL_ALT, "Mangrove Kayaking", "Paddle through tranquil mangrove channels near Cades Bay."),
                (CADES_REEF_IMG, CADES_REEF_ALT, "Cades Reef Snorkel", "Clear water and vibrant marine life over Antigua's south coast reef."),
                (CLASSIC_BEACH_IMG, CLASSIC_BEACH_ALT, "Beach Relaxation", "Finish with swimming and lounging on white sand."),
            ],
            dict(
                best_for="Active travelers and snorkel enthusiasts",
                activity_level="Moderate — kayaking and swimming",
                family="Good for teens; younger children need supervision",
                popular="Kayak snorkel combos, Cades Reef, adventure tours",
            ),
            KAYAK_SNORKEL_IMG,
            KAYAK_SNORKEL_ALT,
            badge="Best Kayak and Snorkel Tour",
            extra_links=[("antigua-half-day-kayak-and-snorkel.html", "Half Day Kayak"), ("best-beaches-in-antigua-for-cruise-passengers.html", "Beach Guide")],
        ),
        "antigua-exclusive-history-and-culture-tour.html": content_tour_page(
            "The Antigua Exclusive History and Culture Tour is a small-group journey to the island's historic south coast — Nelson's Dockyard UNESCO World Heritage site, the Dow's Hill Interpretation Centre, and Shirley Heights lookout with sweeping views over English Harbour. With a maximum of 12 guests, this is the premier history excursion from St John's.",
            [
                "4 hours with small-group visits to key heritage sites.",
                "Nelson's Dockyard — restored Georgian naval dockyard in English Harbour.",
                "Dow's Hill Interpretation Centre with island history exhibits.",
                "Shirley Heights panoramic views over Falmouth and English Harbour.",
                "Easy activity level — short walks at lookout and dockyard.",
            ],
            [
                (NELSONS_DOCKYARD_IMG, NELSONS_DOCKYARD_ALT, "Nelson's Dockyard", "18th-century naval heritage in English Harbour National Park."),
                (SHIRLEY_HEIGHTS_IMG, SHIRLEY_HEIGHTS_ALT, "Shirley Heights", "Historic military lookout with Caribbean panorama."),
                (HISTORY_CULTURE_IMG, HISTORY_CULTURE_ALT, "Cultural Insight", "Expert guides explain Antigua's colonial and maritime past."),
            ],
            dict(
                best_for="History buffs and culture-focused travelers",
                activity_level="Easy — short walks",
                family="Excellent for all ages",
                popular="Nelson's Dockyard, Shirley Heights, history tours",
            ),
            HISTORY_CULTURE_IMG,
            HISTORY_CULTURE_ALT,
            badge="Best History Tour",
            extra_links=[
                ("nelsons-dockyard-from-antigua-cruise-port.html", "Nelson's Dockyard Guide"),
                ("shirley-heights-antigua-guide.html", "Shirley Heights Guide"),
            ],
        ),
        "panoramic-antigua-and-beach-break.html": content_tour_page(
            "Panoramic Antigua and Beach Break is built for passengers who want the island's greatest views and a beach finale in one easy day. A scenic drive crosses Antigua's coastline and hilltop lookouts — including Shirley Heights when included — before a relaxed beach break with refreshments. Bring your camera.",
            [
                "4 hours 30 minutes of scenic driving and beach time.",
                "Small-group format for personalised commentary and photo stops.",
                "Covers south coast viewpoints and island highlights.",
                "Beverage included; easy activity level throughout.",
                "Excellent balance of sightseeing and relaxation.",
            ],
            [
                (PANORAMIC_IMG, PANORAMIC_ALT, "Island Viewpoints", "Coastal roads and hilltop panoramas across Antigua."),
                (SHIRLEY_HEIGHTS_IMG, SHIRLEY_HEIGHTS_ALT, "English Harbour Views", "Sweeping vistas over harbours and Caribbean sea."),
                (CLASSIC_BEACH_IMG, CLASSIC_BEACH_ALT, "Beach Break", "Afternoon swim and lounging on white sand."),
            ],
            dict(
                best_for="Scenic photographers and relaxed explorers",
                activity_level="Easy",
                family="Excellent for families and couples",
                popular="Scenic drives, beach breaks, island tours",
            ),
            PANORAMIC_IMG,
            PANORAMIC_ALT,
            badge="Best Scenic Tour",
            extra_links=[("shirley-heights-antigua-guide.html", "Shirley Heights"), ("classic-beach-day.html", "Classic Beach Day")],
        ),
        "antigua-half-day-kayak-and-snorkel.html": content_tour_page(
            "Antigua Half Day Kayak and Snorkel focuses on the island's south-west coast adventure — paddle a mangrove lagoon in a tandem kayak, reach a secluded beach, then board a boat for snorkelling at Cades Reef. Snacks and beverages are included in this compact 4.5-hour format ideal for cruise schedules.",
            [
                "4 hours 30 minutes — kayak, boat transfer and reef snorkel.",
                "Mangrove lagoon kayaking with expert local guides.",
                "Boat ride to Cades Reef for open-water snorkelling.",
                "Snack and beverage included; moderate fitness required.",
                "Small-group tours with return-to-ship policies.",
            ],
            [
                (HALF_DAY_KAYAK_IMG, HALF_DAY_KAYAK_ALT, "Mangrove Lagoon", "Peaceful paddle through sheltered coastal mangroves."),
                (CADES_REEF_IMG, CADES_REEF_ALT, "Cades Reef", "Snorkel over coral gardens in clear Caribbean water."),
                (KAYAK_SNORKEL_IMG, KAYAK_SNORKEL_ALT, "Secluded Beach", "Quiet beach stop between kayak and snorkel segments."),
            ],
            dict(
                best_for="Kayak and snorkel enthusiasts with limited time",
                activity_level="Moderate — paddling and swimming",
                family="Good for active families with teens",
                popular="Half-day kayak, Cades Reef snorkel, mangroves",
            ),
            HALF_DAY_KAYAK_IMG,
            HALF_DAY_KAYAK_ALT,
            badge="Best Kayak and Snorkel Tour",
            extra_links=[("antigua-kayak-snorkel-and-beach.html", "Full Kayak &amp; Beach Tour")],
        ),
    }
